### PR TITLE
Anam_TestCase

### PR DESCRIPTION
**Pull request by anam88**
Hi teammates. 
Welcome to Anam_TestCase

:)

### CODE REVIEW

**Comment by anam88** [comment]
Can anyone review my code? - Anam

**Comment by shoaibkhan131** [comment]
hey there

**Review by LuisaFRojas — COMMENTED** [review]
Hey Anam!
looking goood!

**Review by anam88 — COMMENTED** [review]
reviewing my own testcase- because I am lost-Anam

**Review by AnelZhaksybergenova — APPROVED** [review]
good

**Pull request merged**
